import express from "express";
import authRoutes from "./routes/auth.routes.js";
import adminRoutes from "./routes/admin.routes.js";
import sellerRoutes from "./routes/seller.routes.js";
import deliveryBoyRoutes from "./routes/deliveryBoy.routes.js";
import deliveryOrderRoutes from "./routes/deliveryOrder.routes.js";
import deliveryAdminRoutes from "./routes/admin.deliveryBoy.routes.js";
import sellerBlockRoutes from "./routes/seller.Block.routes.js";
import blockDeliveryBoyRoutes from "./routes/blockdeliveryboy.routes.js";
import medicineRoutes from "./routes/medicine.routes.js";
import doctorRoutes from "./routes/doctor.routes.js";
import locationRoutes from "./routes/location.routes.js";
import bookingRoutes from "./routes/booking.routes.js";
import availabilityRoutes from "./routes/doctor.availability.routes.js";
import consultationroutes from "./routes/consultation.routes.js";
import blockDoctorRoutes from "./routes/block.doctor.routes.js";
import healthReportRoutes from "./routes/healthReport.routes.js";
import cartRoutes from "./routes/cart.routes.js";
import deliveryDetailsRoutes from "./routes/DeliveryDetails.routes.js";
import orderRoutes from "./routes/order.routes.js";
import orderQueryRoutes from "./routes/orderQuery.routes.js";
import commissionsRoutes from "./routes/commissions.routes.js";
import sellerEarningsRoutes from "./routes/seller.earnings.routes.js";
import stripeRoutes from "./routes/stripe.routes.js";
import restockRoutes from "./routes/restock.routes.js";
import doctorRevenueRoutes from "./routes/doctor.revenu.routes.js";
import doctorGetRoutes from "./routes/doctor.get.routes.js";
const router = express.Router();

router.use("/doctor", doctorRoutes);
router.use("/booking", bookingRoutes);
router.use("/availability", availabilityRoutes);
router.use("/locations", locationRoutes);
router.use("/auth", authRoutes);
router.use("/admin", adminRoutes);
router.use("/medicines", medicineRoutes);
router.use("/seller", sellerRoutes);
router.use("/delivery", deliveryBoyRoutes);
router.use("/delivery", deliveryOrderRoutes);
router.use("/admin/delivery", deliveryAdminRoutes);
router.use("/admin/sellerblock", sellerBlockRoutes);
router.use("/admin/deliveryboy", blockDeliveryBoyRoutes);
router.use("/consultation", consultationroutes);
router.use("/admin/doctor", blockDoctorRoutes);
router.use("/health-report", healthReportRoutes);
router.use("/cart", cartRoutes);
router.use("/delivery-details", deliveryDetailsRoutes);
router.use("/orders", orderRoutes);
router.use("/orders", orderQueryRoutes);
router.use("/commissions", commissionsRoutes);
router.use("/seller-earnings", sellerEarningsRoutes);
router.use("/stripe", stripeRoutes);
router.use("/restock", restockRoutes);
router.use("/doctor-revenue", doctorRevenueRoutes);
router.use("/doctor-get", doctorGetRoutes);
export default router;
